site_name: spatialcsv

site_url: https://TJHomer.github.io/spatialcsv

repo_url: https://github.com/TJHomer/spatialcsv

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Examples:
          - examples/example.ipynb
          - examples/add_csv.ipynb
          - examples/folium.ipynb
          - examples/vectors.ipynb
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/TJHomer/spatialcsv/issues
    - API Reference:
          - spatialcsv module: spatialcsv.md
          - spatialfolium module: spatialfolium.md
